[build-system]
requires = ["setuptools>=62"]
build-backend = "setuptools.build_meta"

[project]
name = "weight"
version = "1.0.0"
description = "A simple command-line weight tracking tool"
requires-python = ">=3.14"

dependencies = [
	"platformdirs>=4.11",
	"plotext>=6.1",
]

[project.scripts]
weight = "weight.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]
